// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/crux.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/mailchimp.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$5 from "./apps/site.ts";
import * as $0 from "./functions/requestToParam.ts";
import * as $$$0 from "./loaders/categoryFromUrl.ts";
import * as $$$$$$0 from "./sections/BlogPost.tsx";
import * as $$$$$$1 from "./sections/BlogPosts.tsx";
import * as $$$$$$2 from "./sections/BlogPostsByCategory.tsx";
import * as $$$$$$3 from "./sections/CategoryHero.tsx";
import * as $$$$$$4 from "./sections/Faq.tsx";
import * as $$$$$$5 from "./sections/Footer.tsx";
import * as $$$$$$6 from "./sections/GenericFilterBlogPost.tsx";
import * as $$$$$$7 from "./sections/Header.tsx";
import * as $$$$$$8 from "./sections/Hero.tsx";
import * as $$$$$$9 from "./sections/ImageTextCards.tsx";
import * as $$$$$$10 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$11 from "./sections/InstagramEmbed.tsx";
import * as $$$$$$12 from "./sections/Logos.tsx";
import * as $$$$$$13 from "./sections/MainPost.tsx";
import * as $$$$$$14 from "./sections/Testimonials.tsx";
import * as $$$$$$15 from "./sections/Theme/Theme.tsx";

const manifest = {
  "functions": {
    "site/functions/requestToParam.ts": $0,
  },
  "loaders": {
    "site/loaders/categoryFromUrl.ts": $$$0,
  },
  "sections": {
    "site/sections/BlogPost.tsx": $$$$$$0,
    "site/sections/BlogPosts.tsx": $$$$$$1,
    "site/sections/BlogPostsByCategory.tsx": $$$$$$2,
    "site/sections/CategoryHero.tsx": $$$$$$3,
    "site/sections/Faq.tsx": $$$$$$4,
    "site/sections/Footer.tsx": $$$$$$5,
    "site/sections/GenericFilterBlogPost.tsx": $$$$$$6,
    "site/sections/Header.tsx": $$$$$$7,
    "site/sections/Hero.tsx": $$$$$$8,
    "site/sections/ImageTextCards.tsx": $$$$$$9,
    "site/sections/ImageWithParagraph.tsx": $$$$$$10,
    "site/sections/InstagramEmbed.tsx": $$$$$$11,
    "site/sections/Logos.tsx": $$$$$$12,
    "site/sections/MainPost.tsx": $$$$$$13,
    "site/sections/Testimonials.tsx": $$$$$$14,
    "site/sections/Theme/Theme.tsx": $$$$$$15,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/crux.ts": $$$$$$$$$$$1,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$2,
    "site/apps/deco/mailchimp.ts": $$$$$$$$$$$3,
    "site/apps/deco/records.ts": $$$$$$$$$$$4,
    "site/apps/site.ts": $$$$$$$$$$$5,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
